### ISSUE TITLE
Smooth page load experience on mobile devices

### ISSUE THREAD

**Issue by maraf** [maraf/Money#253]
Especially on mobile devices, where the computing and network power is lower, it doesn't look good the experience from entering the URL, through loading screen to the page display or login navigation.

- [x] #276 - Add some kind of animation to the load UX.
- [x] #265 - ~~Make better integration with initial authentication (token validation).~~
- [x] #267 - PWA spashscreen background.
- [x] #267 - PWA native topbar background should be blue.
