### ISSUE TITLE
Balances

### ISSUE THREAD

**Issue by maraf** [maraf/Money#337]
The idea is to have an option to input month income and mark some expences as "fixed" to show per-month/per-year balance.

Why marking expences as fixed? Because there are some, which are possibly quite high and these will "destroy" graphs in every month. One the other side, fixed expences will not be shown in the bar graph, only in expense overview.

**API**
- [x] #339 - Allow to mark expense as fixed
- [x] #340 - Creating incomes.
- [x] #373 - Expenses and incomes per-month.

**Blazor**
- [x] #344 - Allow to mark expense as fixed.
- [x] #343 - Creating incomes. 
- [x] #372 - Compare expenses with incomes per month.
